name: Atualizar Pagina HTML

on:
  push:
    paths:
      - 'dados.xlsx' # Dispara a automação sempre que este arquivo mudar

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Executar script de conversao
        run: python gerar_html.py

      - name: Salvar e publicar novo HTML
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Atualizacao automatica da pagina HTML" || exit 0
          git push
